### ISSUE TITLE
Duplicate "New Site Archived" alerts

### ISSUE THREAD

**Issue by morisy** [MuckRock/Klaxon#1]
So far, I've received four "New Site Archived" emails from Klaxon for this run:

https://api.www.documentcloud.org/admin/addons/addonevent/568/change/

It has caught a few correct updates, but it seems like it's not consistently realizing it previously had caught the site?

I also don't see any way to get the run ID, but let me know if there's anything else I can pull (not sure if that would be something useful to include in the alerts for diagnostic purposes?).

**Comment by duckduckgrayduck** [comment]
I think this was an intermittent issue- when Klaxon runs, it checks to see if the site has been seen by the Wayback machine in the past. If archived_snapshots in the response json  is empty, it will archive the page and send that email. I suspect that requests was having issues connecting with Wayback, which defaults to an empty json response, and thus Klaxon thought this site hasn't been seen before. I will add an OR statement to check  if a timestamp exists in the event data, if it does, it will escape this behavior. 

Pushed a change to my repo, evaluating if it works, then will merge

**Comment by morisy** [comment]
Great! Will drop a note if I see it again.

**Comment by duckduckgrayduck** [comment]
Seems to have been fixed by #2
