### ISSUE TITLE
Character encoding not working properly in UX elements

### ISSUE THREAD

**Issue by morisy** [MuckRock/Klaxon#6]
![Screenshot 2023-10-31 at 11 24 57 AM](https://github.com/MuckRock/Klaxon/assets/136939/6c4e89b2-6e22-4000-8439-60f4d9b924a1)

There appears one some character encoding issues with the apostrophe and I'm guessing an "X" button in the user dialogue.

**Comment by duckduckgrayduck** [comment]
Fixed this

**Comment by duckduckgrayduck** [comment]
I've noticed that the issue may re-appear if you  had run Klaxon before and haven't cleared out your browsing history/cache as it is using the cached klaxon.html @morisy just heads up
