### ISSUE TITLE
Edit Klaxon Runs

### ISSUE THREAD

**Issue by mdoksta** [MuckRock/Klaxon#7]
Hi there!
Two observations:
- Is there a way to edit Klaxon monitors after having launched them?
- In the overview of running Klaxon monitors ("Add ons in progress") every job has the same title which makes it confusing if I want to stop a monitor.
Best,
Martin

**Comment by duckduckgrayduck** [comment]
Scheduled Add-Ons, including Klaxon, can be edited by clicking on Schedule & history from the left sidebar. You can toggle through the pages of  the scheduled Add-Ons to find the one that corresponds to the one you want to edit and then click on the pencil icon next to the one you do want to edit. 

Thanks for the feedback on the latter, I'll investigate

**Comment by mdoksta** [comment]
Many thanks!

**Comment by duckduckgrayduck** [comment]
The latter request isn't unique to Klaxon, but all Add-Ons, so I've added it as a request here:
https://github.com/MuckRock/documentcloud-frontend/issues/629

**Comment by duckduckgrayduck** [comment]
Hey @mdoksta your second point about having unique titles has been merged in as a feature across all Add-Ons today, so you should see the URL of the site you are monitoring in the progress bar later today
