### ISSUE TITLE
Ensure bookmarklet JavaScript specifies iframe source

### ISSUE THREAD

**Issue by gregoryfoster** [MuckRock/Klaxon#9]
The [deployed bookmarklet JavaScript code](https://documentcloud-klaxon.s3.amazonaws.com/inject.js) does not match the (presumably?) canonical repository code in one important way.  [Line 62](https://github.com/MuckRock/Klaxon/blob/89df26a6ea4433765cc3402c76335b9209cd4e90/bookmarklet/inject.js#L62), which specifies the iframe source, is commented out in the repository version of the `inject.js` file.  Without that, the iframe fails to open and a same origin policy violation is triggered for every `postMessage` call.

**Comment by duckduckgrayduck** [comment]
I can't recall why I ever commented it out in the repo in the first place, but thanks for catching this.
